# Generated by Django 3.1.7 on 2021-04-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
