# Generated by Django 3.1.7 on 2021-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210404_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='unlike',
            new_name='unlikes',
        ),
    ]
